id: IDBABEB5D
ocr_import_info:
  timestamp: '2023-09-29T10:46:50.948987+00:00'
  batch_id: batch-28f5
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 14:59:00.152647+00:00
last_modified: 2023-09-29 14:59:00.152656+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN22919
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN22919
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་གསང་བ་འདུས་པའི་རྒྱུད་ཀྱི་འགྲེལ་པ་ཁག་གཉིས།
  languages:
  - bo
  author: རྒྱུད་ཆེན་ཀུན་དགའ་དོན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9579054535306425
  ocr_word_median_confidence_index: 0.99838077
bases:
  I4CN10344:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CN10344
      total_pages: 730
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CN10344.txt
    statistics:
      ocr_word_median_confidence_index: 0.99958915
      ocr_word_mean_confidence_index: 0.9635183052873171
  I4CN10345:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CN10345
      total_pages: 650
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4CN10345.txt
    statistics:
      ocr_word_median_confidence_index: 0.9950430299999999
      ocr_word_mean_confidence_index: 0.9511398785341421
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
